version: "3.7"

services:
  database_fin_api_test_unit:
    image: postgres
    container_name: database_fin_api_test_unit
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
